/**
 * Valid operation types exposed by the metrics API.
 */
export type OperationType = 'income' | 'outcome'

/**
 * Valid business lines exposed by the metrics API.
 */
export type BusinessType = 'B2B' | 'B2C'

/**
 * Valid financial categories exposed by the metrics API.
 */
export type Category = 'administrative' | 'operational' | 'others' | 'sales' | 'suppliers'

/**
 * Response body returned by GET /api/metrics/facets.
 */
export interface FacetsResponse {
  /**
   * Sorted list of operation types available in the dataset.
   * Valid values are 'income' and 'outcome'.
   */
  operation_types: OperationType[]

  /**
   * Sorted list of business lines present in the dataset.
   * Valid values are 'B2B' and 'B2C'.
   */
  business_types: BusinessType[]

  /**
   * Sorted list of categories present in the dataset.
   * Valid values are 'administrative', 'operational', 'others', 'sales', and 'suppliers'.
   */
  categories: Category[]

  /**
   * Earliest movement date available in the dataset.
   * Format: YYYY-MM-DD.
   */
  min_date: string

  /**
   * Latest movement date available in the dataset.
   * Format: YYYY-MM-DD.
   */
  max_date: string
}

/**
 * Single anomaly row returned by GET /api/metrics/alerts.
 */
export interface AlertEntry {
  /**
   * Period label generated by the backend aggregation.
   * This feature relies on the endpoint default group_by=month, so values are expected in YYYY-MM format.
   */
  period: string

  /**
   * Total outcome amount recorded for the period.
   * Currency formatting is applied by the UI.
   */
  outcome_total: number

  /**
   * Backend-provided baseline average used to detect the spike.
   * The API returns a numeric average only; it does not expose the averaging window in the payload.
   */
  baseline_average: number

  /**
   * Increase ratio over the baseline average.
   * Example: 0.3 represents a 30% increase and should be rendered as 30% in the UI.
   */
  increase_ratio: number
}

/**
 * Response body returned by GET /api/metrics/alerts.
 */
export type AlertsResponse = AlertEntry[]

/**
 * Single ranked category row returned by GET /api/metrics/categories/top.
 */
export interface CategoryEntry {
  /**
   * Category identifier for the aggregated total.
   * Valid values are 'administrative', 'operational', 'others', 'sales', and 'suppliers'.
   */
  category: Category

  /**
   * Operation type that was aggregated for this ranking.
   * The comparison feature must request 'income'.
   */
  operation_type: OperationType

  /**
   * Sum of all amounts for this category after filters are applied.
   * Currency formatting is applied by the UI.
   */
  total_amount: number
}

/**
 * Response body returned by GET /api/metrics/categories/top.
 */
export type TopCategoriesResponse = CategoryEntry[]